baseurl = "https://barinchiro.com/"
title = "Barin Chiropractic"
author = ""
googleAnalytics = ""
defaultContentLanguage = "en"
language = "en-US"
paginate = 3

theme = "terrassa"
themesDir = "themes" # Not necessary on production sites

[params]
    description = "Barin Chiropractic - Your Chiropractor in Allston-Brighton"
    favicon = "images/favicon.png"
    logo = "images/logo.png"

[params.homepage_meta_tags]
    meta_description = "Barin Chiropractic - Your Chiropractor in Allston-Brighton"
    meta_og_title = "Barin Chiropractic"
    meta_og_type = "website"
    meta_og_url = "https://barinchiro.com"
    meta_og_image = "https://barinchiro.com/images/logo.png"
    meta_og_description = "Barin Chiropractic - Your Chiropractor in Allston-Brighton"
    meta_twitter_card = ""
    meta_twitter_site = ""
    meta_twitter_creator = ""

[params.hero]
    textColor = "#ffffff" # Empty for default color

[params.cta] # Call To Action 
    show = true
    cta = "Contact"
    link = "contact" # Relative URL

[params.separator] # Separators between sections on the home page
    show = false

[params.fa] # Font Awesome options
    version = "5.7.2"
    integrity = "sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP"

[params.form] # Contact form
    netlify = false
    action = "https://formsubmit.io/send/e56205c6-8bf2-4399-b550-f2af7f6076ac"
    method = "POST"
    inputNameName = "name"
    inputNameLabel = "Name"
    inputNamePlaceholder = "Your name"
    inputEmailName = "email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Your email"
    inputMsgName = "message"
    inputMsgLabel = "Write something"
    inputMsgLength = 750
    inputSubmitValue = "Send"

[params.posts]
    showAuthor = true
    showDate = true
    showTags = true
    dateFormat = "Monday, Jan, 2006"

[params.contact] # Contact info
    email = ""
    phone = "617-782-5100"
    skype = ""
    address = "556 Cambridge St.Allston MA, 02134"

[params.social]
    twitter = ""
    facebook = ""
    github = ""
    gitlab = ""
    codepen = ""
    instagram = ""
    pinterest = ""
    youtube = ""
    linkedin = ""
    weibo = ""
    mastodon = ""
    tumblr = ""
    flickr = ""
    "500px" = ""

[params.copy] # Copyright
    copy = "" # Empty for default content

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = true
        respectDoNotTrack = true
        useSessionStorage = true
    [privacy.instagram]
        disable = true
        simple = true
    [privacy.twitter]
        disable = true
        enableDNT = true
        simple = true
    [privacy.vimeo]
        disable = true
        simple = true
    [privacy.youtube]
        disable = true
        privacyEnhanced = true
